name: meritendance
description: "Meritendance (Darshan) - Face Attendance for Campus."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  intl: ^0.20.0
  http: ^1.2.2
  camera: ^0.11.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  fake_async: ^1.3.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
